quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

quarkus.rest-client.enrichment-api.url=http://localhost:8080
quarkus.rest-client.enrichment-api.scope=jakarta.inject.Singleton

